version : "3.8"

services:
  demo-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8976:80"
      - "8977:443"
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html

  database:
    image: mariadb
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db_blog
      MYSQL_ROOT_PASSWORD: password
    # adminer:
    #   image: adminer
    #   restart: always
    #   ports:
    #     - "1333:8080"
volumes:
  data: